name: Test Redhat-compatible platforms

on:
  workflow_dispatch:
    inputs:
      platforms:
        description: 'Platforms'
        default: '["centos:7", "quay.io/centos/centos:stream8", "quay.io/centos/centos:stream9",
                   "redhat/ubi9:latest", "redhat/ubi10:latest",
                   "rockylinux:8", "rockylinux:9", "almalinux:10",
                   "oraclelinux:7", "oraclelinux:8", "oraclelinux:9",
                   "amazonlinux:2", "amazonlinux:2022", "amazonlinux:2023",
                   "fedora:latest"]'

jobs:
  redhat-compat-matrix:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l -eo pipefail {0}
    strategy:
      matrix:
        os: ${{ fromJson(inputs.platforms) }}
      fail-fast: false
    container:
      image: ${{ matrix.os }}
      options: --cpus 2
    steps:
#    - name: Prerequisites
#      run: |
#        yum install -y tar gzip
    - uses: actions/checkout@v3
      with:
        submodules: false
#    - run: |
#        git config --global --add safe.directory '*'
#        # git submodule update --init --recursive
    - name: Set up Classico
      run: |
        V=1 ./sbin/setup
    - name: Installations
      run: |
        ./bin/getgcc --modern
    - name: Summary
      run: |
        echo "/etc/os-release:"; cat /etc/os-release
        echo "/etc/redhat-release:"; cat /etc/redhat-release || true
        echo "uname -a: $(uname -a)"
        echo "bash: $BASH_VERSION"
        echo "System Python: $(/usr/bin/python --version)"
        echo "Python: $(python --version)"
        echo "pip list:"; python -m pip list -v
        echo "System gcc: $(/usr/bin/gcc --version | head -1)"
        echo "gcc: $(gcc --version | head -1)"
        echo "glibc: $(./bin/glibcver)"
        echo "libstdc++: $(./bin/libstdc++ver)"
        echo "binutils: $(ld --version | head -1)"
